# Generated by Django 3.2.19 on 2023-05-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0, verbose_name='Лайк')),
                ('dislike', models.IntegerField(default=0, verbose_name='Дизлайк')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedislike', to='videos.profile', verbose_name='Автор')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedislike', to='videos.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
